# Data Proprocessing

In [24]:
# !pip install tensorflow

In [51]:
import cv2 as cv
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.image import load_img, img_to_array

from src.xml_parser import extract_image_filenames

In [4]:
df = pd.read_csv(r"..\output\labels.csv")
df.head()

filepath  xmin  xmax  ymin  ymax
0    ..\input\number-plates\annotations\Cars0.xml   226   419   125   173
1    ..\input\number-plates\annotations\Cars1.xml   134   262   128   160
2   ..\input\number-plates\annotations\Cars10.xml   140   303     5   148
3  ..\input\number-plates\annotations\Cars100.xml   175   214   114   131
4  ..\input\number-plates\annotations\Cars101.xml   167   240   202   220

In [6]:
# getting all the co-ordinatess from all the xml files
df.iloc[:,1:5].values

array([[226, 419, 125, 173],
       [134, 262, 128, 160],
       [140, 303,   5, 148],
       ...,
       [ 98, 297, 102, 191],
       [ 85, 247, 196, 259],
       [ 70, 262, 198, 271]], dtype=int64)

In [9]:
# exteacted all the image paths from the dataframe
image_paths = extract_image_filenames(df)

In [29]:
image_paths[12]

'../input/number-plates/images\\Cars109.png'

In [32]:
# reading the image using OpenCV
image_array = cv.imread(image_paths[12])

In [33]:
# extracting the height and width of the image
height, width = image_array.shape[:2]

In [36]:
# using target size to make sure all the images are the same size
load_image = load_img(image_paths[12], target_size=(224,224))

In [38]:
# normalizing the pixel values so that they range from 0 to 1 instead of 0 to 255
# to help make the model converge faster and improve performance
img_to_array(load_image)/255

array([[[0.2627451 , 0.28235295, 0.11372549],
        [0.4       , 0.40784314, 0.24705882],
        [0.3882353 , 0.39607844, 0.22352941],
        ...,
        [0.32156864, 0.40392157, 0.45490196],
        [0.32941177, 0.40784314, 0.45882353],
        [0.34901962, 0.41960785, 0.4745098 ]],

       [[0.27058825, 0.2901961 , 0.12156863],
        [0.4       , 0.40392157, 0.24705882],
        [0.3882353 , 0.4       , 0.22745098],
        ...,
        [0.32941177, 0.40784314, 0.45882353],
        [0.34117648, 0.42352942, 0.47058824],
        [0.35686275, 0.43137255, 0.48235294]],

       [[0.33333334, 0.3529412 , 0.17254902],
        [0.39607844, 0.4117647 , 0.24313726],
        [0.4       , 0.4117647 , 0.24313726],
        ...,
        [0.3764706 , 0.45882353, 0.50980395],
        [0.43137255, 0.5176471 , 0.5647059 ],
        [0.41960785, 0.5019608 , 0.5529412 ]],

       ...,

       [[0.88235295, 0.8901961 , 0.89411765],
        [0.8       , 0.80784315, 0.80784315],
        [0.7764706 , 0

In [50]:
load_image_array = img_to_array(load_image)/255

In [43]:
# extracting the co-ordinate values for sample image
xmin, xmax, ymin, ymax = df.iloc[:,1:5].values[12]

In [45]:
print(xmin, xmax, ymin, ymax)

115 278 116 153


In [47]:
# normalizing the co-ordinate values
print(xmin/width, xmax/width, ymin/height, ymax/height)

0.2875 0.695 0.4344569288389513 0.5730337078651685


In [49]:
normalized_labels = (xmin/width, xmax/width, ymin/height, ymax/height)
normalized_labels

(0.2875, 0.695, 0.4344569288389513, 0.5730337078651685)

In [53]:
# independent variable
np.array(load_image_array, dtype=np.float32)

array([[[0.2627451 , 0.28235295, 0.11372549],
        [0.4       , 0.40784314, 0.24705882],
        [0.3882353 , 0.39607844, 0.22352941],
        ...,
        [0.32156864, 0.40392157, 0.45490196],
        [0.32941177, 0.40784314, 0.45882353],
        [0.34901962, 0.41960785, 0.4745098 ]],

       [[0.27058825, 0.2901961 , 0.12156863],
        [0.4       , 0.40392157, 0.24705882],
        [0.3882353 , 0.4       , 0.22745098],
        ...,
        [0.32941177, 0.40784314, 0.45882353],
        [0.34117648, 0.42352942, 0.47058824],
        [0.35686275, 0.43137255, 0.48235294]],

       [[0.33333334, 0.3529412 , 0.17254902],
        [0.39607844, 0.4117647 , 0.24313726],
        [0.4       , 0.4117647 , 0.24313726],
        ...,
        [0.3764706 , 0.45882353, 0.50980395],
        [0.43137255, 0.5176471 , 0.5647059 ],
        [0.41960785, 0.5019608 , 0.5529412 ]],

       ...,

       [[0.88235295, 0.8901961 , 0.89411765],
        [0.8       , 0.80784315, 0.80784315],
        [0.7764706 , 0

In [54]:
# dependent variable
np.array(normalized_labels, dtype=np.float32)

array([0.2875   , 0.695    , 0.4344569, 0.5730337], dtype=float32)